config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :courses

  root 'users#index'

  get '/sign-up' => 'registrations#new', as: :signup
    post '/sign-up' => 'registrations#create'
    get '/sign-in' => 'authentication#new', as: :signin
    post '/sign-in' => 'authentication#create'
    get '/sign-out' => 'authentication#destroy', as: :signout
  
end

app/models/course.rb
class Course < ActiveRecord::Base


end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates :username, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    User.find_by(id: session[:user_id])
  end

  helper_method :current_user

end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to users_path
    else
      @sign_in_error = "Username / password combination is invalid"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to users_path
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
      if @course.save
        redirect_to courses_path
      else
        render :new
      end
  end

  def show
    @course = Course.find(params[:id])
  end

  def edit
    @course = Course.find(params[:id])
  end

  def update
    @course = Course.find(params[:id])
      if @course.update(course_params)
        redirect_to courses_path
      else
        render :edit
      end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
      redirect_to courses_path
  end

  private

  def course_params
    params.require(:course).permit(:title, :day_class)
  end




end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :about, :password, :password_confirmation)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        redirect_to users_path
      else
        render :new
      end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to users_path
      else
        render :edit
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
      redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :about, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authentication/new.html.erb
<%= form_tag signin_path do |f|%>

<% if @sign_in_error %>
  <p>
    <%= @sign_in_error %>
  </p>
<% end %>

  <div>
    <%= label_tag :username %>
  </div>
  <div>
    <%= text_field_tag :username %>
  </div>
  <div>
    <%= label_tag :password %>
  </div>
  <div>
    <%= password_field_tag :password %>
  </div>
  <br>
  <div>
    <%= submit_tag "Sign In" %>
  </div>


<% end %>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>

<div>
  <%= f.label :title %>
</div>
<div>
  <%= f.text_field :title %>
</div>
<div>
  <%= f.label :day_class, "Day class?" %>
</div>
<div>
  <%= f.check_box :day_class %>
</div>
<br>
<div>
  <%= f.submit %>
</div>

<% end %>

app/views/courses/edit.html.erb
<h2>Edit this course</h2>

<%= render 'form' %>

<%= link_to "Back", courses_path %>

app/views/courses/index.html.erb
<h2>Courses Index</h2>
<p> <%= link_to "Add new course", new_course_path %></p>
<br>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Day or night?</th>
      <th>---</th>
      <th>---</th>
    </tr>
  </thead>
  <tbody>
    <% @courses.each do |course| %>
    <tr>
      <td> <%= link_to course.title, course_path(course) %></td>
      <td> <%= course.day_class ? "Day" : "Night" %></td>
      <td> <%= link_to "Edit Course", edit_course_path(course) %></td>
      <td> <%= link_to "Delete Course", course, method: :delete %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Home", users_path %>

app/views/courses/new.html.erb
<h2>Create a new course</h2>

<%= render 'form' %>

<%= link_to "Back", courses_path %>

app/views/courses/show.html.erb
<h2>Look at this sweet course</h2>

<br>
<h3>Title</h3>
<p> <%= @course.title %></p>
<h3>Day or night?</h3>
<p> <%= @course.day_class ? "Day" : "Night" %></p>

<%= link_to "Back", courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalebAtwoodWeek7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <ul>
    <% if current_user %>
    <li><%= link_to current_user.username, user_path(current_user) %></li>
    <li><%= link_to "Sign Out", signout_path%></li>
    <% else %>
    <li><%= link_to "Sign Up", signup_path %></li>
    <li><%= link_to "Sign In", signin_path %></li>
    <% end %>
  </ul>

  <div>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>

  <div>
    <%= f.label :username %>
  </div>
  <div>
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :about %>
  </div>
  <div>
    <%= f.text_field :about %>
  </div>
  <div>
    <%= f.label :password %>
  </div>
  <div>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
  </div>
  <div>
    <%= f.password_field :password_confirmation %>
  </div>
  <br>
  <div>
    <%= f.submit "Update User" %>
  </div>

<% end %>

app/views/users/index.html.erb
<h2>Users Index</h2>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>About</th>
      <th>---</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td> <%= link_to user.username, user_path(user) %></td>
      <td> <%= user.about %></td>
      <% if current_user %>
      <td> <%= link_to "Edit", edit_user_path(user) %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
<h2> <%= link_to "Courses Index", courses_path %></h2>
<% end %>

app/views/users/show.html.erb
<h3> <%= @user.username %></h3>

<h4>About</h4>
<p> <%= @user.about %></p>

<br>
<%= link_to "Home", users_path %>